name: memo_chat
description: "A Chatting App Developed by Harsh H. Rajpurohit (Google Me)"
publish_to: "none"
version: 1.0.2+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # For using cupertino icons
  cupertino_icons: ^1.0.8

  # Firebase core services
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.1.6

  # Google sign-in
  google_sign_in: ^6.2.2

  # Image picker and caching
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Emojis
  emoji_picker_flutter: ^3.1.0

  # Notifications
  flutter_local_notifications: ^17.1.2
  flutter_notification_channel: ^2.0.0

  # ✅ Replaced: Correct package to save images
  image_gallery_saver: ^2.0.3

  # Permissions
  permission_handler: ^11.3.0

  # HTTP & Auth
  http: ^1.2.2
  googleapis_auth: ^1.6.0

  # Optional: for downloading images
  dio: ^5.8.0+1

  # Animations
  lottie: ^3.2.0

  # Gemini AI
  google_generative_ai: ^0.4.3

  # Date formatting
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
